<a href="https://colab.research.google.com/github/devanshmesson/Competitive-programming/blob/master/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy library for python (Numerical Python)

Use:

1.   This library is used to work with multidimensional arrays.
2.   Provides attributes and mathematical functions which really provides a better way of handling data for processing.

Why Numpy and what was wrong with Python lists?  
 
1. It consumes relatively very less memory in comparison to Python lists.
2. Because it ensures continuous memory allocation(efficient storage), it is faster that Python list.
3. In addition, Numpy provides much better mathematical fucntions which makes it easy that Python list.

#Comparison between a Python list and a Numpy array
Conclusion: Numpy array is memory efficient

In [289]:
import sys
python_list=[1,2,3,4,5]
numpy_array=np.array([1,2,3,4,5])

print("Memory consumed by python list:",end=" ")
print(sys.getsizeof(1)*len(python_list),end=" ")
print("bytes")

print("Memory consumed by numpy array:",end=" ")
print(numpy_array.itemsize*numpy_array.size,end=" ")
print("bytes")

Memory consumed by python list: 140 bytes
Memory consumed by numpy array: 40 bytes


#Some important Numpy functions and attributes


##1. 1D and 2D array creation
1.1 Creating an array of list through numpy  
1.2 Creating a 2D array by creating an array of multiple lists through numpy   
1.3 Creating a 2D array of custom size filled with zeroes  
1.4 Creating an array containing elements from 0 to n-1   
1.5 Create an array of n elements in which elements are equidistant from each other in a specified range    
1.6 Create an array with random values  
1.7 Creating an identity matrix of size n x n

In [290]:
#importing numpy library
import numpy as np

#Creating an array of list through numpy 
arr=np.array([4,3,2,1])
print("1D array:")
arr

1D array:


array([4, 3, 2, 1])

In [291]:
#Creating a 2D array by creating an array of multiple lists through numpy 
arr2d=np.array([[9,8,0],
                [6,0,5],
                [10,3,1]])
print("2D array:")
arr2d

2D array:


array([[ 9,  8,  0],
       [ 6,  0,  5],
       [10,  3,  1]])

In [292]:
#Creating a 2D array of custom size filled with zeroes
zero=np.zeros((2,5)) #2 rows and 5 columns
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [293]:
#Creating an array containing elements from 0 to n-1
arr_cont=np.arange(15)
arr_cont

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [294]:
#Create an array of n elements in which elements are equidistant from each other in a specified range
equi_arr = np.linspace(1,10,4) #1 is the starting number, 10 is the stopping number, 4 represents no. of elements
equi_arr

array([ 1.,  4.,  7., 10.])

In [295]:
#Create an array with random values
rand=np.empty((2,3)) #2 rows and 3 columns
rand

array([[4.64264792e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [296]:
#Creating an identity matrix of size n x n
iden=np.identity(5) #5 rows and 5 columns
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##2.Manipulating the structure of 2D array
2.1 Reshaping a 2D array  
2.2 Converting 2D array to 1D array  
2.3 Convert a Nummpy array to python list  
2.4 Transpose a 2D array  
2.5 Flatten a 2D array

In [297]:
#Reshaping a 2D array
arr2d.reshape((9,1))

array([[ 9],
       [ 8],
       [ 0],
       [ 6],
       [ 0],
       [ 5],
       [10],
       [ 3],
       [ 1]])

In [298]:
#Converting 2D array to 1D array
arr2d.ravel()

array([ 9,  8,  0,  6,  0,  5, 10,  3,  1])

In [299]:
#Converting a numpy array to python list
arr.tolist()


[4, 3, 2, 1]

In [300]:
#Transpose a 2D array
arr2d.T

array([[ 9,  6, 10],
       [ 8,  0,  3],
       [ 0,  5,  1]])

In [301]:
#Flatten a 2D array
arr2d.flat
for element in arr2d.flat:
  print(element,end=" ")


9 8 0 6 0 5 10 3 1 

#Numpy axis (important concept)
An axis represents a dimension  
In 1D array, axis0 is present  
In 2D array, axis0,axis1 are present

axis0 represents column and axis1 represents row

#3.Mathematical Numpy functions and attributes
3.1 Return the index of maximum element in a 2D array  
3.2 Return the index of minimum element in a 2D array  
3.3 Return the position of all elements of the array suppossing the array is sorted  
3.4 Return sum of all elements of 2D or 1D array  
3.5  Return the index of maximum element of each column in a 2D array  
3.6  Return the index of maximum element of each row in a 2D array  
3.7 Return the position of elements of a particular row of the 2d array suppossing that particular row of the 2d array is sorted  
3.8 Return the position of elements of a particular column of the 2d array suppossing that particular column of the 2d array is sorted  
3.9 Taking square root of all elements of the array/ 2d array  
3.10 Return number of dimensions of array/2d array   
3.11 Return number of elements in array/2d array  
3.12 Return minimum element in the array/2d array  
3.13 Return maximium element in the array/2d array    
3.14 Return indexes of elements in array/2d array where elements are greater than 5  
3.15 Count all non-zero elements in array/2d array  
3.16 Return indexes of all non-zero elements in array/2d array  
3.17 Add corresponding elements of two 2d arrays  
3.18 Multiply corresponding elements of two 2d arrays  
3.19 Return total bytes consumed by the array



In [302]:
#3.1 Return the index of maximum element in a 2D array
np.argmax(arr2d)
##After flattening the array, it finds the index of the maximum element

6

In [303]:
#3.2 Return the index of minimum element in a 2D array
np.argmin(arr2d)
##After flattening the array, it finds the index of the minimum element

2

In [304]:
#3.3 Return the position of all elements of the array suppossing the array is sorted
np.argsort(arr) 

array([3, 2, 1, 0])

In [305]:
#3.4 Return sum of all elements of 2D or 1D array
arr2d.sum()

42

In [306]:
#3.5 Return the index of maximum element of a each column in a 2D array
arr2d.argmax(axis=0)
#axis0 represents column

array([2, 0, 1])

In [307]:
#3.6 Return the index of maximum element of a each row in a 2D array
arr2d.argmax(axis=1)
#axis1 represents row

array([0, 0, 0])

In [308]:
#3.7 Return the position of elements of a particular row of the 2d array suppossing that particular row of the 2d array is sorted
arr2d.argsort(axis=1)
#axis1 represents row
#In the output below, 2 in first column first row means that element at first row and first column must be at first row third column, In order to sort first row

array([[2, 1, 0],
       [1, 2, 0],
       [2, 1, 0]])

In [309]:
#3.8 Return the position of elements of a particular column of the 2d array suppossing that particular column of the 2d array is sorted
arr2d.argsort(axis=0)
#axis0 represents column 
#In the output below, 1 in first column first row means that element at first row and first column must be at second row first column, In order to sort first column

array([[1, 1, 0],
       [0, 2, 2],
       [2, 0, 1]])

In [310]:
#3.9 Taking square root of all elements of the array/ 2d array
np.sqrt(arr)

array([2.        , 1.73205081, 1.41421356, 1.        ])

In [311]:
#3.10 Return number of dimensions of array/2d array
arr2d.ndim

2

In [312]:
#3.11 Return number of elements in array/2d array
arr2d.size

9

In [313]:
#3.12 Return minimum element in the array/2d array
arr.min()

1

In [314]:
#3.13 Return maximium element in the array/2d array
arr2d.max()

10

In [315]:
#3.14 Return indexes of elements in array/2d array where elements are greater than 5
np.where(arr2d>5)

#In the output, first array contains the indexes of elements column-wise

#Matrix is indexed as follows:
# 0 0 0
# 1 1 1
# 2 2 2

#Our 2d array is :
# 9 8 0
# 6 0 5
# 10 3 1

#Hence output is 0,0,1,2
#--------------------------------------------------------------------------------

#Similary, In the output, second array contains the indexes of elements row-wise

#Matrix is indexed as follows:
# 0 1 2
# 0 1 2
# 0 1 2

#Our 2d array is :
# 9 8 0 
# 6 0 5
# 10 3 1

#Hence output is 0,1,0,0

(array([0, 0, 1, 2]), array([0, 1, 0, 0]))

In [316]:
#3.15 Count all non-zero elements in array/2d array
np.count_nonzero(arr2d)

7

In [317]:
#3.16 Return indexes of all non-zero elements in array/2d array
np.nonzero(arr2d)

#In the output, first array contains the indexes of elements > 0 column-wise

#Matrix is indexed as follows:
# 0 0 0
# 1 1 1
# 2 2 2

#Our 2d array is :
# 9 8 0
# 6 0 5
# 10 3 1

#Hence output is [0, 1, 2, 0, 2, 1, 2] which is rearranged as: [0, 0, 1, 1, 2, 2, 2]
#--------------------------------------------------------------------------------

#Similary, In the output, second array contains the indexes of elements row-wise

#Matrix is indexed as follows:
# 0 1 2
# 0 1 2
# 0 1 2

#Our 2d array is :
# 9 8 3 
# 6 4 5
# 10 3 1

#Hence output is [0,1,0,2,0,1,2]

(array([0, 0, 1, 1, 2, 2, 2]), array([0, 1, 0, 2, 0, 1, 2]))

In [318]:
#3.17 Add corresponding elements of two 2d arrays

arr1=np.array([[9,8,0],
                [6,0,5],
                [10,3,1]])

arr2=np.array([[1,2,0],
                [3,0,4],
                [5,1,0]])

arr1+arr2


array([[10, 10,  0],
       [ 9,  0,  9],
       [15,  4,  1]])

In [319]:
#3.18 Multiply corresponding elements of two 2d arrays
arr2*arr1

array([[ 9, 16,  0],
       [18,  0, 20],
       [50,  3,  0]])

In [320]:
#3.19 Return total bytes consumed by the array
arr2d.nbytes

72